# Generated by Django 2.1.3 on 2018-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('Id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Acc_number', models.BigIntegerField()),
                ('Acc_name', models.CharField(max_length=50)),
                ('Bank', models.CharField(max_length=50)),
                ('Acc_balance', models.FloatField(default=0.0)),
                ('Uup', models.TextField()),
            ],
        ),
    ]
