# Generated by Django 2.1.3 on 2018-11-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='Id',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='Uup',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
