# Generated by Django 2.1.3 on 2018-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181125_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='Uup',
        ),
        migrations.AddField(
            model_name='accounts',
            name='Id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='Bank',
            field=models.CharField(max_length=3),
        ),
    ]
